### PR TITLE
Hide answers for exercises

### PR DESCRIPTION
**Pull request by satsie**
I'm not sure if this is possible or desired, but wanted to propose hiding the answers for the exercises, starting with chapter 3. This would be similar to the various "Click to see xyz" sections in the book. 

Is there a way I can run this locally to check that the change works?

If this is a good idea, I'm happy to update the rest of the exercises so the answers are initially collapsed.

### CODE REVIEW

**Review by brunoerg — COMMENTED** [review]
Strong Concept ACK

**Comment by willcl-ark** [comment]
Hey Stacie, if you want to check this locally you need to install the dependencies in https://github.com/chaincodelabs/onboarding-to-bitcoin-core/blob/master/asciidoc_workflow.adoc (I should probably make these clearer within that doc...). That is to say:

1. asciidoctor
2. asciidoctor-diagram
3. mermaid-cli

With those you can regenerate index.html file (which is the static page the web server hosts) using 
```
asciidoctor -r asciidoctor-diagram index.adoc
```
FYI I think you'll want somethign closer to:

```asciidoc

.Click for answer
[%collapsible]
====
Contextual checks require some knowledge of the current "state", e.g. ChainState, chain tip or UTXO set.

Context-free checks only require the information required in the transaction itself.

See <<glozow-tx-mempool-validation,glozow's tx mempool validation>> for more info.
====

```

For them. Internal document cross-references use the `<<link-anchor, custom link text>>` format, whereas external links use the `https://link.com[custom link text^]` format (the `^` makes links open in a new tab, which I think is nicer).

Also when asciidoctor revolves around text "blocks", which is what the `====` represent there, so you won't need the `+` between lines to keep lines together in a block, once you've blocked them with a `====` block marker :)

**Comment by satsie** [comment]
Thank you @willcl-ark ! I got everything running locally and am in the process of making the answers collapsible items for the rest of the exercises. I will rebase and mark the PR as ready for review when I am done.

One thing I ran into was if I put the collapsible block inside of a [description list](https://docs.asciidoctor.org/asciidoc/latest/lists/description/) (as denoted by the `::` at the end of each exercise), I could not edit the collapsible block's toggle text. I want the blocks to say "Click for answer", but instead they always render the default "Details" toggle text. 

Because of this, I removed the `::` that makes the question a description list, and converted it to regular ordered list by adding a `.` at the beginning.

It would be nice for the collapsible blocks with answers to be indented, so they line up with the questions,  but I haven't been able to find a way to do this. Open to any suggestions!

**Comment by willcl-ark** [comment]
So I guess you want something like:

```adoc
== Exercises

[qanda]
What is the difference between contextual and context-free validation checks?::
+
.Click for answer
[%collapsible]
====
Contextual checks require some knowledge of the current "state", e.g. ChainState, chain tip or UTXO set.

Context-free checks only require the information required in the transaction itself.

For more info, see <<glozow-tx-mempool-validation,glozow's notes>> on transaction "Validation and Submission to the Mempool".
====

What are some examples of each?::
+
.Click for answer
[%collapsible]
====
context-free:

. `tx.isCoinbase()`
. https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/consensus/tx_check.cpp#L25-L28[0 &#8804; tx_value &#8804; MAX_MONEY^]
. https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/policy/policy.cpp#L88[tx not overweight^]

contextual:

. https://github.com/bitcoin/bitcoin/tree/4b5659c6b115315c9fd2902b4edd4b960a5e066e/src/validation.cpp#L671-L692[check inputs are available^]
====

```

`+` is linking the next block to the previous block.

**Comment by satsie** [comment]
That did the trick! Thank you. This is ready for review now :)

**Comment by willcl-ark** [comment]
Thanks, this looks great!

**Pull request merged**
