### PR TITLE
Add a glossary of common terms

### PR DESCRIPTION
**Pull request by adam2k**
Resolves https://github.com/chaincodelabs/onboarding-to-bitcoin-core/issues/50

Add a glossary of common terms after the appendix.

### CODE REVIEW

**Comment by willcl-ark** [comment]
Hey Adam, this looks like a great start to this section!

I added a second commit with some minor fixups which I noticed on a first read. Perhaps you could check if you are happy with them?

I pushed a version with these two commits to https://obc.256k1.dev/#_glossary already, so you can see what it looks like live (which you can also do locally by running `asciidoctor -r asciidoctor-diagram --verbose --trace index.adoc; open index.html` FYI).

**Comment by willcl-ark** [comment]
Just fixed (my own) tab indentations :)

**Comment by adam2k** [comment]
@willcl-ark the changes look good! I was able to see them in the git diff, but I didn't see them on the website. Maybe something is still cached for me or you reverted those changes? I tried in two different browsers and I couldn't see the glossary.

**Comment by willcl-ark** [comment]
Try refreshing the browser cache (ctrl + shift + r or perhaps cmd+shift+r?)

**Comment by willcl-ark** [comment]
Merged in https://github.com/chaincodelabs/onboarding-to-bitcoin-core/commit/e9538fc43caa6a76d62be513c3af0abbb714a024

**Review by Theghost256 — APPROVED** [review]

**Review by Ricchkdbanks — APPROVED** [review]

**Pull request closed without merging**
